version: "3"
services: 
  mysql:
    image : mysql:8.0
    restart: always
    ports: 
      - 3306:3306
    networks: 
      - node-app
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=vendinguser
      - MYSQL_PASSWORD=vendingpass
      - MYSQL_DATABASE=vendingdb
      - MYSQL_DIALECT=mysql
      - MYSQL_HOST=mysql
  api-server:
    image : "vernding-server:latest"
    ports: 
      - 4000:4000
    networks: 
      - node-app
    depends_on: 
      - mysql
networks: 
  node-app:
    driver: bridge
